# Generated by Django 3.1.2 on 2020-10-25 01:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_score', models.IntegerField(default=5000)),
                ('turn_index', models.IntegerField(default=1)),
                ('last_turn', models.BooleanField(default=False)),
                ('status', models.CharField(default='active', max_length=10)),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_current_player', models.BooleanField(default=False)),
                ('player_order', models.IntegerField(default=1)),
                ('total_score', models.IntegerField(default=0)),
                ('had_last_turn', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farkle.game')),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('current', 'current'), ('over', 'over')], max_length=15)),
                ('score', models.IntegerField(default=0)),
                ('available_dice', models.IntegerField(default=6)),
                ('scrubbed', models.BooleanField(default=False)),
                ('dice_1', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], null=True)),
                ('dice_2', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], null=True)),
                ('dice_3', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], null=True)),
                ('dice_4', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], null=True)),
                ('dice_5', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], null=True)),
                ('dice_6', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farkle.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farkle.player')),
            ],
        ),
        migrations.CreateModel(
            name='DiceSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dice_1', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], null=True)),
                ('dice_2', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], null=True)),
                ('dice_3', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], null=True)),
                ('dice_4', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], null=True)),
                ('dice_5', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], null=True)),
                ('dice_6', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], null=True)),
                ('score', models.IntegerField(default=0)),
                ('score_type', models.CharField(blank=True, max_length=30, null=True)),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farkle.turn')),
            ],
        ),
    ]
